import type { Metadata } from "next"
import { Montserrat, Source_Sans_3 } from "next/font/google"
import "./globals.css"
import { type ReactNode } from "react"

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
    style: ["normal", "italic"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const sourceSans3 = Source_Sans_3({
    variable: "--font-source-sans-3",
    subsets: ["latin"],
    style: ["normal", "italic"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${sourceSans3.variable} antialiased`}>{children}</body>
        </html>
    )
}
