name: tests

on:
    push:
        branches:
            - develop
            - main
            - master
            - workos
    pull_request:
        branches:
            - develop
            - main
            - master
            - workos

jobs:
    ci:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.61.0-noble

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup pnpm
              uses: pnpm/action-setup@v6
              with:
                  cache: true

            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                  registry-url: https://registry.npmjs.org
                  cache: pnpm

            - name: Install Linux dependencies
              run: |
                  apt-get update
                  apt-get install -y \
                  build-essential \
                  pkg-config \
                  libcairo2-dev \
                  libpango1.0-dev \
                  libjpeg-dev \
                  libgif-dev \
                  librsvg2-dev \
                  libpixman-1-dev

            - name: Install Node Dependencies
              run: pnpm install

            - name: Run tests
              env:
                  HOME: /root
              run: pnpm run tests
